version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.6

jobs:
  build:
    docker:
      - image: 'circleci/python:latest'

    steps:
      - checkout
      # - run: mkdir bucket && echo "lorum ipsum" > bucket/build_asset.txt
      - aws-s3/sync:
          from: .
          to: 's3://edaoud.com'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400" \
          overwrite: false